name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-lint-prettier.yml@feat/better-sharable-actions
  test:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@feat/better-sharable-actions
  test-zk:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test-zk.yml@feat/better-sharable-actions
  merge:
    name: Merge artifacts
    runs-on: ubuntu-latest
    needs: [test, test-zk]
    if: always()
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          # The name of the artifact that the artifacts will be merged into
          # Optional. Default is 'merged-artifacts'
          name: 'content'

          # A glob pattern matching the artifacts that should be merged.
          # Optional. Default is '*'
          pattern: 'content*'

          delete-merged: true
