name: Head branch workflow

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  test:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@main
  test-sol-zksync:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@main
    secrets: inherit
    with:
      mode: "CHANGED"
      zksync: true
      ROOT_DIR: "zksync"
