name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-lint-prettier.yml@feat/better-sharable-actions
  test:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test.yml@feat/better-sharable-actions
  test-zk:
    uses: bgd-labs/github-workflows/.github/workflows/foundry-test-zk.yml@feat/better-sharable-actions
